[feat] DB 생성
PSR-Co/SERVER pull request #10
Opened 2023-07-21 19:30 UTC by sojungpp

## 🌱 이슈 번호
close #1 

<br>

## 💬 기타 사항
- ENUM 변수명 확인해주세요 !
- DB 같이 정한대로 우선 생성했는데, 같이 의논하고 싶은 부분이 있어서 리뷰로 달아두겠습니다
- 늦어서 죄송합니다 사랑합니다

2023-07-21 19:43 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/cs/entity/Notice.kt
> +        var imgKey: String
imgKey / ~imgKey로 이름 통일 필요할 것 같아요!

2023-07-21 19:43 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/inquiry/entity/Inquiry.kt
> +        var answer: String
answer는 답변 생성 전에는 null 가능이라 @notnull 제외시켰습니다!

2023-07-21 19:43 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/product/entity/product/ProductImg.kt
> +        var imgKey: String
imgKey / ~imgKey로 이름 통일 필요할 것 같아요!

2023-07-21 19:43 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/user/entity/User.kt
> +        var profileImgKey: String,
imgKey / ~imgKey로 이름 통일 필요할 것 같아요!

2023-07-22 01:40 UTC, chaerlo127 approved these changes
바빴을텐데 수고 너무 많았숨니다🤍🤍
title, content도 앞에 엔터티 이름을 적지 않았으니 imgKey도 엔터티 이름 붙이지 않고 통일하는건 어떨까욤

2023-07-22 05:01 UTC, psyeon1120 requested changes
저도 그냥 imgKey로 통일하는게 좋을 것 같아요오
왜 저 새벽에 작업한겨ㅠㅠㅠㅠ 오늘 화이팅이예요오

2023-07-22 05:01 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/chat/entity/ChatRoom.kt
> +        @JoinColumn(nullable = false, name = "sender_user_idx")
idx로 쓴 이유가 있나용??

2023-07-22 05:01 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/cs/entity/Faq.kt
> +        @NotNull
Enum 쓴 부분은 `@Enumerated(EnumType.STRING)`가 필요할 것 같습니다!
지금 DB에는 tinyint로 되어있어용

2023-07-23 13:01 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/chat/entity/ChatRoom.kt
> +        @JoinColumn(nullable = false, name = "sender_user_idx")
fault .. 수정햇웁니다

2023-07-23 13:01 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/cs/entity/Faq.kt
> +        @NotNull
감사합니당당 수정완!!

2023-07-23 13:09 UTC, psyeon1120 commented
😍

2023-07-23 13:09 UTC, psyeon1120 approved these changes
😍

2023-07-23 13:11 UTC, merged