[feat] 요청하기 API 생성
PSR-Co/SERVER pull request #53
Opened 2023-08-04 16:36 UTC by psyeon1120

## 🌱 이슈 번호
close #52

<br>

## 💬 기타 사항
- 코멘트 단거 확인해주세용

2023-08-04 16:37 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
> +                if (orderReq.websiteUrl.isNullOrBlank()) orderReq.websiteUrl = null
빈 string이 들어왔을 때도 null로 만들고 싶어서 dto에서 websiteUrl만 var로 했는데 이래도 괜찮은감?

2023-08-04 16:41 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/order/dto/OrderReq.kt
> +    @field:Size(max = 100, message = "이름은 최대 100자입니다.")
db에는 100자로 되어있길래 이렇게 해놨는데 맞나용?

2023-08-05 06:45 UTC, chaerlo127 approved these changes
아따 깔끔하다 ~ 🍀

2023-08-05 06:45 UTC, chaerlo127 commented on src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
> +                if (orderReq.websiteUrl.isNullOrBlank()) orderReq.websiteUrl = null
`String? = null` 요 부분 있으면 자동으로 null 처리가 되더라구영
(저도 어제 API 만들면서 안 사실,,, ㅎㅅㅎ)

2023-08-05 06:45 UTC, chaerlo127 commented on src/main/kotlin/com/psr/psr/order/dto/OrderReq.kt
> +    @field:Size(max = 100, message = "이름은 최대 100자입니다.")
혹시 몰라서 찾아보니까 한글도 한글자를 1로 인식하나봐여!!
[클릭 히어](https://okky.kr/questions/232069)

2023-08-05 06:45 UTC, chaerlo127 commented on src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
> +                if (orderReq.websiteUrl.isNullOrBlank()) orderReq.websiteUrl = null
isNullOrBlank에 대해서 알아감니다 최고💛

2023-08-05 08:05 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
> +                if (orderReq.websiteUrl.isNullOrBlank()) orderReq.websiteUrl = null
웅 나도 `String? = null`로 해놨는데 null로 들어오면 괜찮거등
근데 ""나 "  "이거로 들어오면 그냥 고대로 저장해버려서 null로 바꿔주고 싶어써

2023-08-05 10:55 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
> +                if (orderReq.websiteUrl.isNullOrBlank()) orderReq.websiteUrl = null
공식문서 봤더니 data class에서 val이나 var 둘 다 선언해서 써도 되는 것 같기도 .. !
![스크린샷 2023-08-05 오후 7 55 03](https://github.com/PSR-Co/SERVER/assets/90022940/35c2ba82-094f-4c27-a926-1a550a766676)
[링크](https://kotlinlang.org/docs/data-classes.html)

2023-08-05 11:03 UTC, sojungpp requested changes
수고하셨어욥!!!!!!! 화면이랑 엔티티 생성에서 빼먹은(내가..) 부분 커멘트 남겨놨는데 확인 한 번만 부탁!

2023-08-05 11:03 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/order/dto/OrderAssembler.kt
> +        )
제가.. 빼먹었는데 웹사이트는 null 가능이에요 .. ! (수정해주실 수 잇을까요 샘)

2023-08-05 11:03 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/order/entity/Order.kt
> +        var websiteUrl: String?,
NotNull 어노테이션 빼주실 수 잇을까요 주륵

2023-08-05 11:54 UTC, psyeon1120 commented on src/main/kotlin/com/psr/psr/order/entity/Order.kt
> +        var websiteUrl: String?,
수정했습니다아

2023-08-05 11:54 UTC, sojungpp commented on src/main/kotlin/com/psr/psr/order/entity/Order.kt
> +        var websiteUrl: String?,
감사함다잉

2023-08-05 11:54 UTC, sojungpp approved these changes

2023-08-05 11:55 UTC, merged